#!/usr/bin/env bash
# Validate everything in this repository, with the real tools, in Docker.
#
#   ./run-tests.sh
#
# 1. shell syntax (sh -n) for setup.sh and scripts/
# 2. YAML syntax of every configuration file
# 3. promtool check config + check rules + test rules (the 6 alert unit tests)
# 4. caddy validate on the Caddyfile and its routes
# 5. docker compose config on a throw-away .env (no secrets, no containers started)
#
# Needs Docker. Nothing is installed on the host and nothing is left running.
set -euo pipefail
cd "$(dirname "$0")"

PROM_IMAGE="${PROM_IMAGE:-prom/prometheus:v3.14.0}"
CADDY_IMAGE="${CADDY_IMAGE:-caddy:2.11.4}"
STACK="$PWD/stack"

echo "==> shell syntax"
for f in stack/setup.sh stack/scripts/*.sh; do sh -n "$f"; done
echo "  SUCCESS"

echo "==> YAML syntax"
python3 - <<'PY'
import glob, sys
try:
    import yaml
except ImportError:
    print("  SKIPPED (PyYAML not installed on this host)"); sys.exit(0)
files = (glob.glob("stack/*.yaml") + glob.glob("stack/prometheus/**/*.yml", recursive=True)
         + glob.glob("stack/grafana/provisioning/*/*.yml"))
for f in files:
    yaml.safe_load(open(f))
print(f"  SUCCESS ({len(files)} files)")
PY

echo "==> promtool check config"
docker run --rm -v "$STACK/prometheus:/etc/prometheus:ro" \
  --entrypoint promtool "$PROM_IMAGE" check config /etc/prometheus/prometheus.yml

echo "==> promtool check rules"
docker run --rm -v "$STACK/prometheus:/etc/prometheus:ro" \
  --entrypoint sh "$PROM_IMAGE" -c 'promtool check rules /etc/prometheus/rules/*.yml'

echo "==> promtool test rules (6 alerts)"
docker run --rm -v "$STACK/prometheus:/etc/prometheus:ro" \
  --entrypoint sh "$PROM_IMAGE" -c 'promtool test rules /etc/prometheus/tests/*.test.yml'

echo "==> caddy validate"
# caddy validate needs the basic-auth file the Caddyfile imports; this is a throw-away
# hash of a random value, used only to make the config parse. Never a real credential.
tmp="$PWD/.tmp-validate"
trap 'rm -rf "$tmp"' EXIT
rm -rf "$tmp"; mkdir -p "$tmp"
printf 'admin $2a$14$ZG9ja2VyLXRlc3QtaGFzaGVudsvJSBz1rQjXwAaVjHHo0zCTjpDkK\n' > "$tmp/caddy_admin_users"
docker run --rm -e DOMAIN=monitoring.example.com -e CADDY_TLS=internal \
  -v "$STACK/Caddyfile:/etc/caddy/Caddyfile:ro" -v "$STACK/caddy/routes.d:/etc/caddy/routes.d:ro" \
  -v "$tmp:/run/secrets:ro" \
  "$CADDY_IMAGE" caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile 2>&1 | tail -n 3

echo "==> docker compose config"
compose() {
  if docker compose version >/dev/null 2>&1; then docker compose "$@"
  elif command -v docker-compose >/dev/null 2>&1; then docker-compose "$@"
  else echo "  SKIPPED (Docker Compose v2 not found)"; return 0
  fi
}
# The secret files are generated by setup.sh on the server; create empty placeholders so the
# project can be resolved here without them. They are removed again right after.
mkdir -p stack/secrets
placeholders=""
for s in grafana_admin_password caddy_admin_users; do
  if [ ! -e "stack/secrets/$s" ]; then : > "stack/secrets/$s"; placeholders="$placeholders stack/secrets/$s"; fi
done
DOMAIN=monitoring.example.com CADDY_TLS=internal compose -f stack/compose.yaml config -q
# shellcheck disable=SC2086
[ -n "$placeholders" ] && rm -f $placeholders
rmdir stack/secrets 2>/dev/null || true
echo "  SUCCESS"

echo "All checks passed."
